//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsukifudousan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDB
    {
        public int CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Manager { get; set; }
        public string ContactInformation { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string RegistrationDate { get; set; }
        public string LastUpdateDate { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
    }
}
